### ISSUE TITLE
405 OCR  memory quick use out & Can it use "GPU" device

### ISSUE THREAD

**Issue by AmazingYi** [openvinotoolkit/openvino_notebooks#573]
**Describe the bug**
   Memory quick  use  out when  run 405 code  in commd line .and  system broke down .  

 **Expected behavior**
   run code in command line and set  use_popup  True.It works and show  recongenized characters at first  ,but soon,the   memory quickly grow up and the system broke down

**Screenshots**
   screen got stuck and can't  boot after a force reboot

 **Installation instructions (Please mark the checkbox)**
openvino  2022.1 pip installed ,conda env ,ubuntu 20.04 ,paddle cpu pip installed . 

** Environment information **
python 3.8(conda) env  , I 5 1135G7
 
**Additional context**
I also have a question  that can it  use "GPU"  device to infer . I tried to modified "CPU" to "GPU" . but it turn a error seems like "unsurport  dynamic layer ".  I install the NEO installration and  Core().avilibaledevice  show "GPU" in list.

**Comment by raymondlo84** [comment]
I notice a few time there is a memory issue with the webcam demo,.. Will look deeper into it next @adrianboguszewski

**Comment by adrianboguszewski** [comment]
@AmazingYi thanks for this bug report. Answering your question: no, you cannot use GPU with this notebook as it uses the Dynamic Shapes feature. Dynamic Shapes require to use CPU.

**Comment by raymondlo84** [comment]
Please update the documentation in the notebooks. @zhuo-yoyowz

**Comment by zhuo-yoyowz** [comment]
> Please update the documentation in the notebooks. @zhuo-yoyowz

Done updating the documentation for notebook 405 on the iGPU issue.

**Comment by adrianboguszewski** [comment]
The bug is confirmed. There is memory leakage in the OCR model. We have to wait for the OpenVINO team to fix it.

**Comment by adrianboguszewski** [comment]
@riverlijunjie It looks like the bug still exists after updating to 2022.2...

**Comment by adrianboguszewski** [comment]
The bug is fixed but this is a natural behavior of this feature showing increasing memory. However, it shouldn't be quick.
